language: java
jdk: oraclejdk8
after_success: ./.travis.after_success.sh
sudo: required
dist: trusty
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
before_cache:
- rm -rf $HOME/.m2/repository/com/vaadin/vaadin-frontend-maven-plugin
env:
  global:
  - secure: Yqzal035M0hn8yZchtHv2pJzc5/M/vLz32nY0zOFfvycSHqVpV/+M2WYOhbkve7l3O73ckYSd4TlI6BJHlsce8/KkYvfBfGJLBCbbTFn/NDBz39AL5mLUHWOuFandIEV4fIAnFX/h0Um5U+wp8W3snWZJq1ArbXMRnrjdTYM1f5j84FzbyO4fms3lr4nVfWBkOR1Uz99l0QweBbFu+7yRZ5OvDd/D/DYWEYiPEDbjGeV6JN0cPFEwoVqp0Ud5kx3IV1yyn9CuvAMGAOV9XdeVRVWIgwrqkBTRbrNxmF7jb+hT4eZ6VPDQrMjMvH9jukyxpNg+dhdyEfQOfMpMVdE0bM0Lf0B9B8xGPncFe5c1Ji93ky3OrjEX0IBdsEFdexyqK5nmWkNMmW3E9cOiLHgKUXXiz6K8RDqHgrIR7WTHL/gITxzR/a08Gk6C6Kr7NUYGuSaDA8CTqqwQUmxi6K83G2L+BqPBmMdaDEJwbw0fSLoAMwSQ5qUTekBGixryd0qaZLAJFxCDvjtsukI10j2F1E+XeFdK8V6EJKw9g455ejLzgM+DLl/4NwftDmX3jGnCgf19EFtAzmoSq1zFZKQYrc/xwKCpZRA+PMkrVnFlTmN8Qi3p0J5/IFTueB3NHf2kYCnd9uwKPXSlclr3FbtY+8JzbKKBKnnqXdmcYEObuE=
  - secure: JOIKkvnmf3U+6ch90CZjXx3GPj6AHtaOBHnlSTlU4cxVB1OT/Y2qFqCZHIYbb/SbHyN/18QPOTFxIuM6kN+y2sa0NxFUhoQaZBp5hB7su9PadwbAJWO1sGhJ/fOpaOvctw4/uATgL2Eq2mry0tnpB7guhjSuto3XAP/nZJfuMltcf5cdIBN8UbHh7A8nLec7dbo87a6Fi4LZG35YFF/2Jr2DtfCAEOzjSb8hjKYp+IE2g1f//xzlSyxWA+X13/ru5CX9Fpc1SmInffrYVK3pUM6dfIBPbAq8pcRgxzE8AcTzJcOABQiruROczWWQlqC0J/RtEyHst7uqE3J4mSKqdYUYK72pY4b7rP+aXbQrP7s3/FqRrrwoAEVVHHoQMo3fyVwBo5Kwqz4U89xMpS8PDtr1tAi15DPma5t97JNL9rnR2vsna5/19RMw6Rb+2xx0X3OifmTz1znwK2MnQROxRvLUTMIQ6PFSz0PinvCM3ANNpvWVY9Y7NarNCLsH9FobpVwQI1QsZcXDjEI7NUq0l6Bp99LHyd8uh6xNwviCY0qyZMEV/G6yhaazK522vHnAmkBrZlXCPWKH603nOMeeAKWEZprBQv/LHTG1gkM/i+s3c1WavVpsLNvADVQafnr0Tvc64y5mddk+HAA+KVsE8UdJISa5yd6jGfVQv9aG5b0=
